version: '2'
 
services:
 
  # Build the container using the client Dockerfile
  client:
      build: ./twitter-analysis-frontend
  
  # Build the container using the backend Dockerfile
  backend:
      build: ./backend
 
  # Build the container using the nginx Dockerfile
  nginx:
    build: ./nginx
    # Map Nginx port 80 to the local machine's port 4200
    ports:
      - "4200:80"
      - "9000:9000"
    # Link the client container so that Nginx will have access to it
    links:
      - client
      - backend
